version: "3"
services:
  frontend:
    build:
      context: ./site-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:3001
  backend:
    build:
      context: ./site-backend
      dockerfile: Dockerfile
    ports:
    - "3001:3001"
    env_file:
    - .env.local
    depends_on:
    - mariadb
    command: [./migrate.sh]
  mariadb:
    image: mariadb:latest
    env_file:
    - .env.local
    volumes:
    - ./data:/var/lib/mariadb